from typing import Dict, Any

class LocatorScorer:
    """
    Component 7: Locator Scoring System
    Weights different element indicators according to their structural resilience.
    """
    WEIGHTS = {
        "accessibility_name": 95,
        "aria_label": 92,
        "data_attribute": 90,
        "text_match": 84,
        "grounded_id": 80,
        "css_selector": 52,
        "xpath": 28
    }

    @classmethod
    def calculate_score(cls, locator_type: str, element_data: Dict[str, Any]) -> float:
        """
        Calculates selector confidence score, applying minor penalties if locators
        are overly long or contain numbers (which indicate autogenerated tags).
        """
        base_score = cls.WEIGHTS.get(locator_type, 50)
        locator_str = str(element_data.get("locator", ""))

        # Penalty: overly long selectors indicates high fragility
        if len(locator_str) > 100:
            base_score -= 10
            
        # Penalty: digits in class names often indicate autogenerated hashes
        if locator_type == "css_selector" and any(char.isdigit() for char in locator_str):
            base_score -= 15

        return max(5, base_score)
