import os
import json
import logging
from abc import ABC, abstractmethod
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class BaseAdapter(ABC):
    """
    Component 5: Base Site Adapter
    Declarative and procedural interface for site-specific overlays and selectors.
    """
    def __init__(self, site_name: str):
        self.site_name = site_name
        self.knowledge = self.load_knowledge_pack()

    def load_knowledge_pack(self) -> Dict[str, Any]:
        """
        Loads the site versioned knowledge pack JSON config.
        """
        base_dir = os.path.dirname(os.path.dirname(__file__))
        path = os.path.join(base_dir, "site_knowledge", self.site_name, "knowledge.json")
        try:
            with open(path, "r", encoding="utf-8") as f:
                logger.info(f"Loaded site knowledge pack for {self.site_name}")
                return json.load(f)
        except Exception as e:
            logger.warning(f"No knowledge pack config found at {path}: {e}")
            return {}

    @abstractmethod
    def identify_site(self, url: str) -> bool:
        pass

    @abstractmethod
    def get_custom_validators(self, node_id: str) -> List[str]:
        pass

    def clean_elements(self, raw_elements: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Removes dynamic CSS class properties or structural garbage to clean element tokens.
        """
        cleaned = []
        for el in raw_elements:
            el_copy = dict(el)
            # Remove autogenerated class attributes if present in selectors
            selector = el_copy.get("selector", "")
            if "." in selector:
                # Remove class parts from selector (e.g. div.a8f9xq -> div)
                parts = selector.split(".")
                el_copy["selector"] = parts[0]
            cleaned.append(el_copy)
        return cleaned
